Bump recipes base container to 25.12 (#1399)
Also requires using TOT megatron-fsdp to avoid the error

```
  File "/usr/local/lib/python3.12/dist-packages/megatron_fsdp/utils.py", line 168, in get_mesh_names
    for child_mesh, root_mesh in _mesh_resources.child_to_root_mapping.items()
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: '_MeshEnv' object has no attribute 'child_to_root_mapping'
```

that was fixed in https://github.com/NVIDIA/Megatron-LM/pull/2575

---------

Signed-off-by: Peter St. John <pstjohn@nvidia.com>